:-use_module(library(csv)).


?- csv_read_file('/Users/baray_kaya/Desktop/Knowledge Representation /symbolic-output.csv', Data).
 % with this code we have achieved reading csv file long text format
 
 % output shown in this way :
 % Data = [row('', 'A1', '', 'A2', '', 'A3', '', 'A4', '', 'A5', '', 'A6', '', 'A7', ''), row('I1', h, 0.73, vh, 0.49, h, 0.55, h, 0.61, vh, 1.0, vh, 0.78, m, 0.88), row('I2', z, 1.0, vl, 1.0, h, 1.0, vl, 0.88, m, 0.84, m, 1.0, h, 0.84), row('I3', vh, 0.84, h, 1.0, m, 0.78, h, 0.84, h, 0.67, vh, 0.73, m, 0.96), row('I4', vh, 0.55, h, 0.98, h, 0.49, h, 0.55, vh, 0.73, h, 0.88, h, 0.55), row('I5', h, 0.98, vh, 1.0, vh, 1.0, vh, 1.0, vh, 0.98, h, 0.49, h, 0.67), row('I6', h, 0.98, vh, 0.88, vh, 0.92, h, 0.78, vl, 0.98, h, 0.92, m, 1.0), row('I7', h, 0.96, h, 0.49, h, 0.96, vh, 0.78, h, 0.96, m, 0.92, m, 0.96), row(..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ..., ...)|...].

 



""" I am getting this error :
No permission to call sandboxed `open(_1612,_1614,_1616,_1618)'
Reachable from:
	  csv:phrase_from_file(A,B,C)
	  csv_read_file(A,B,C) """
